name: arq-microsservicos-mba
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    # Kafka Client (Confluent)
    - confluent-kafka[avro]>=2.3.0
    # Avro Serialization
    - fastavro>=1.9.0
    - avro-python3>=1.10.0
    # Utilities
    - faker>=20.0.0
    - requests>=2.31.0
    - pydantic>=2.6.0
    # Database
    - psycopg2-binary>=2.9.9

